[build]
    command = "hugo --gc --minify"
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.87.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"
