[build]
    command = "hugo --gc --minify"
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.87.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

[[redirects]]
    from = "https://practical-aws.netlify.app/"
    to = "https://practical-aws.dev"
    status = 301
    force = true

[[redirects]]
    from = "https://www.practical-aws.dev"
    to = "https://practical-aws.dev"
    status = 301
    force = true